1. Melakukan berbagai operasi yg diberikan dengan numpy

In [2]:
import numpy as np

In [4]:
# buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[1, 5, 11], [55, 15, 55]])
x

array([[ 1,  5, 11],
       [55, 15, 55]])

In [5]:
# tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [6]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x[:, 0]

array([ 1, 55])

In [7]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[1, :]

array([55, 15, 55])

2. Melakukan Operasi yg telah dilakukan menggunakan pytorch dan tensorflow

In [10]:
import torch
import tensorflow as tf

In [11]:
# buat matrix x_t berukuran 2x3 menggunakan pytorch
x_t = torch.tensor([[1, 5, 11], [55, 15, 55]])
x_t

tensor([[ 1,  5, 11],
        [55, 15, 55]])

In [12]:
# tampilkan ukuran dari matrix x_t
x_t.shape

torch.Size([2, 3])

In [13]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_t
x_t[:, 0]

tensor([ 1, 55])

In [14]:
# tampilkan seluruh elemen dari baris kedua dari matrix X_t
x_t[1, :]

tensor([55, 15, 55])

In [15]:
# buat matrix x_t berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[1, 5, 11], [55, 15, 55]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  5, 11],
       [55, 15, 55]], dtype=int32)>

In [16]:
# tampilkan ukuran dari matrix x_tf
x_tf.shape

TensorShape([2, 3])

In [17]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
x_tf[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 55], dtype=int32)>

In [18]:
# tampilkan seluruh elemen dari baris kedua dari matrix X_tf
x_tf[1, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([55, 15, 55], dtype=int32)>