1.buat vector x dengan ukuran 3x1

In [2]:
import numpy as np

In [3]:
# buat vector x dengan ukuran 3x1
x = np.array([[15],
             [11],
             [51]])
x

array([[15],
       [11],
       [51]])

In [4]:
# hitung nilai L2 norm dari vector x
(15**2 + 11**2 + 51**2)**(1/2)

54.286278192559855

2. buat vector v dengan ukuran (3,4)

In [5]:
# buat vector v dengan elemen (3,4)
v = np.array([1, 5, 15])
v

array([ 1,  5, 15])

In [6]:
# hitung nilai L2 norm dari vector v
(1**2 + 5**2 + 15**2)**(1/2)

15.84297951775486

In [7]:
# tampilkan unit vector dari vector v
norm = np.linalg.norm(x) # buat ngitung panjang vector
x_unit = x / norm # buat ngitung unit vector
x_unit

array([[0.27631292],
       [0.20262947],
       [0.93946393]])

In [8]:
# hitung panjang unit vector dari vector v
np.linalg.norm(x_unit)

np.float64(1.0)