Melakukan operasi apapun yang ditentukan dengan numpy



In [5]:
import numpy as np

In [7]:
# buat vector x dengan ukuran 3x1
x = np.array([[15],
             [11],
             [51]])
x

array([[15],
       [11],
       [51]])

In [8]:
# hitung panjang vector x
len(x)

3

In [9]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [10]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [11]:
# akses elemen pertama dari vector x
x[0]

array([15])

In [12]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. Vectors Transposition

In [13]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[15, 11, 51]])

In [14]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [21]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[51,11,15]])
y

array([[51, 11, 15]])

In [22]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([[51],
       [11],
       [15]])

In [23]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [4]:
import torch
import tensorflow as tf

In [7]:
# lakukan transpose pada vector x dan simpan pada variabel x_pt
x_pt = torch.tensor([[51, 15, 11]])
x_pt = x_pt.T
x_pt

tensor([[51],
        [15],
        [11]])

In [8]:
# tampilkan ukuran dari vector x_pt
x_pt.shape

torch.Size([3, 1])

In [10]:
# lakukan transpose pada vector y dan simpan pada variabel y_pt
y_pt = torch.tensor([[51],[11],[15]])
y_pt = y_pt.T
y_pt

tensor([[51, 11, 15]])

In [11]:
# tampilkan ukuran dari vector x_pt
x_pt.shape

torch.Size([3, 1])

In [12]:
# lakukan transpose pada vector x dan simpan pada variabel x_tf
x_tf = tf.Variable([[51, 15, 11]])
x_tf = tf.transpose(x_tf)
x_tf

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[51],
       [15],
       [11]], dtype=int32)>

In [13]:
# tampilkan ukuran dari vector x_tf
x_tf.shape

TensorShape([3, 1])

In [14]:
# lakukan transpose pada vector y dan simpan pada variabel y_tf
y_tf = tf.Variable([[51],[11],[15]])
y_pt = tf.transpose(y_tf)
y_pt

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[51, 11, 15]], dtype=int32)>

In [15]:
# tampilkan ukuran dari vector x_tf
x_tf.shape

TensorShape([3, 1])